/** @format */

import type { Metadata, Viewport } from "next";
import Localfont from "next/font/local";
import "./globals.css";
import TenstackProvider from "@/util/config/Providers/TenstackProvider";

import img from "@/public/Favicon.ico";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};
export const metadata: Metadata = {
  title: "Tamnama Manager",
  description: "Generated by create next app",
  // icons: {
  // },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body>
        <TenstackProvider>{children}</TenstackProvider>
      </body>
    </html>
  );
}
