/** @format */

import type { Metadata, Viewport } from "next";
import Localfont from "next/font/local";
import "@/app/globals.css";
import TenstackProvider from "@/util/config/Providers/TenstackProvider";

import localFont from "next/font/local";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};
export const metadata: Metadata = {
  title: "Tamnama Manager",
  description: "Generated by create next app",
  // icons: {
  // },
};

const iranianSans = localFont({
  src: [
    {
      path: "../public/fonts/IRANSans_Medium.woff2",
      weight: "400",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className={iranianSans.className}>
        <TenstackProvider>{children}</TenstackProvider>
      </body>
    </html>
  );
}
